// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/2/7 09:10:06
const configMerger = require("D:/Files/Desktop/learn-from-zero/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Files/Desktop/learn-from-zero/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/plugins/**/*.{js,ts,mjs}","D:/Files/Desktop/learn-from-zero/composables/**/*.{js,ts,mjs}","D:/Files/Desktop/learn-from-zero/utils/**/*.{js,ts,mjs}","D:/Files/Desktop/learn-from-zero/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/learn-from-zero/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["33"] = "D:/Files/Desktop/learn-from-zero/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
